# Generated by Django 4.0.4 on 2023-02-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(help_text='Full name of Chef', max_length=150, verbose_name='Chef´s name')),
                ('nickname', models.CharField(help_text='Name to display in the interface', max_length=24, verbose_name='Nickname')),
                ('description', models.CharField(help_text='Chef`s short description', max_length=24, verbose_name='Short Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Chef´s user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
