# Generated by Django 4.0.4 on 2023-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
