# Generated by Django 4.0.4 on 2023-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chef_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='description',
            field=models.CharField(help_text='Chef`s short description', max_length=400, verbose_name='Short Description'),
        ),
    ]
