# Generated by Django 4.0.4 on 2023-02-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ingredient name')),
                ('amount', models.CharField(help_text='Open text field to indicate the amount of ingredients', max_length=100, verbose_name='Amount of ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Recipe Category',
                'verbose_name_plural': 'Recipe Categories',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='Description of how to prepare the recipe.', verbose_name='Description')),
                ('cooking_time', models.CharField(help_text='time needed to cook.', max_length=20, verbose_name='Time')),
                ('servings', models.CharField(help_text='Description of how many plates the recipe serve.', max_length=100, verbose_name='Servings')),
                ('procedure_complexity', models.IntegerField(choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Average'), (3, 'Difficult'), (4, 'Very Difficult')], default=2, verbose_name='Complexity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_list', to='recipes.recipecategory')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='users.chef')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient', verbose_name='Ingredients')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
