# Generated by Django 4.0.4 on 2023-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, help_text='time in minutes needed to cook.', null=True, verbose_name='Time'),
        ),
    ]
